---
services: docker

env:
  - distro=debian8
  - distro=debian9
  - distro=ubuntu1604

install:
  - export container_id=$(date +%s)
  - idempotence=$(mktemp)
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

  # Build and run docker container
  - docker pull geerlingguy/docker-$distro-ansible:latest
  - docker run --detach --volume="$(dirname "$TRAVIS_BUILD_DIR")":/etc/ansible/roles:rw --name $container_id --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro geerlingguy/docker-$distro-ansible:latest /lib/systemd/systemd
  - docker exec --tty ${container_id} env TERM=xterm apt-get update -qq
  - docker exec --tty ${container_id} env TERM=xterm apt-get install -y ufw
  - docker ps

script:
  # Run playbook.
  - docker exec --tty $container_id env TERM=xterm ansible-playbook /etc/ansible/roles/ansible-role-nginx/tests/test.yml --syntax-check
  - docker exec $container_id env TERM=xterm env ANSIBLE_FORCE_COLOR=1 ansible-playbook /etc/ansible/roles/ansible-role-nginx/tests/test.yml -vvv
  - docker exec $container_id ansible-playbook /etc/ansible/roles/ansible-role-nginx/tests/test.yml | tee -a $idempotence
  - tail $idempotence | grep -q 'changed=0.*failed=0' && (printf 'Idempotence test pass') || (printf 'Idempotence test fail' && exit 1)

  # Tests
  - docker exec --tty ${container_id} env TERM=xterm apt-get install -y curl
  - docker exec --tty ${container_id} env TERM=xterm nginx -t
  # check sirbot config
  - docker exec --tty ${container_id} env TERM=xterm sh -c "grep 'server_name sirbot.pyslackers.local;' /etc/nginx/sites-enabled/sirbot"
  - docker exec --tty ${container_id} env TERM=xterm cat /etc/nginx/sites-enabled/sirbot
  # check default nginx config
  - docker exec --tty ${container_id} env TERM=xterm cat /etc/nginx/nginx.conf
  # check pyslackers config
  - docker exec --tty ${container_id} env TERM=xterm sh -c "grep 'return 301 https://pyslackers.com/traviscitest' /etc/nginx/sites-enabled/pyslackers"
  # check gzip flag is toggle-able
  - docker exec --tty ${container_id} env TERM=xterm sh -c "if [ -z \"$(grep 'gzip on' /etc/nginx/sites-enabled/nongzipped_site)\" ]; then true; else false; fi"

  # curl websites
  - "docker exec --tty ${container_id} env TERM=xterm curl localhost -v -H 'Host: sirbot.pyslackers.local' | grep '502 Bad Gateway'"
  - "docker exec --tty ${container_id} env TERM=xterm curl localhost -v -H 'Host: pyslackers.local' | grep 'Location: https://pyslackers.com/traviscitest'"
  - "docker exec --tty ${container_id} env TERM=xterm curl localhost -v -H 'Host: nongzip.local' | grep '502 Bad Gateway'"
  - "docker exec --tty ${container_id} env TERM=xterm curl localhost -v -H 'Host: basicauth.local' | grep '401 Authorization Required'"
  - "docker exec --tty ${container_id} env TERM=xterm curl localhost -v -H 'Host: basicauth.local' --user foo:bar | grep '502 Bad Gateway'"
  - "docker exec --tty ${container_id} env TERM=xterm curl localhost -v"
